version: '3.1'

services:
  db:
    image: postgres:12-alpine
    container_name: postgresql-db
    expose:
      - 5432
    ports:
      - "5434:5432"
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: teste_gft
   
  javaservice:
    image: matheusy/teste-gft
    container_name: teste-gft-app
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - 8090
    ports:
      - "8090:8090"
    restart: always
    depends_on:
      - db