version: '3.1'

services:
  db:
    image: postgres:12-alpine
    container_name: postgresql-db
    expose:
      - 5432
    ports:
      - "5434:5432"
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: test_sibs
   
  javaservice:
    image: matheusy/test_sibs
    container_name: test_sibs_app
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - 8090
    ports:
      - "8090:8090"
    restart: always
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db